name: Build and Ship

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    
    - name: Install Dependencies
      run: sudo apt-get install -y graphviz doxygen libjansson-dev zlib1g-dev libzstd-dev

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release -DLIBTMJ_TEST=ON -DLIBTMJ_DOCS=ON -DLIBTMJ_ZSTD=ON -DLIBTMJ_ZLIB=ON .

    - name: Build
      run: cmake --build .

    - name: Test
      run: ctest

    - name: Create Docs Artifact
      uses: actions/upload-pages-artifact@v1.0.4
      with:
        path: docs/html/

    - name: Create libtmj Artifact
      uses: actions/upload-artifact@v3
      with:
        name: libtmj-master
        path: lib/*
        if-no-files-found: error
        retention-days: 1

  Pages:
    needs: Build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Publish Documentation
        uses: actions/deploy-pages@v1.2.2
